apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-n131
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-n131@sha256:988da155f385c54a6b08c8b0adb150c1197c4c5da2ed5a8acba19f7c981a40f6
        name: my-nodejs
        resources: {}
status: {}
